# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'exchange' do
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

end

target 'exchange-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for exchange-tvOS

  target 'exchange-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
